# Generated by Django 4.1.2 on 2023-09-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScrapedProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("locality", models.CharField(max_length=255)),
                ("price_range", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("area", models.CharField(max_length=100)),
                ("property_type", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("url", models.URLField()),
            ],
        ),
    ]
